### ISSUE TITLE
Powershell cmdlets missing

### ISSUE THREAD

**Issue by camenard** [DamagedDingo/JSM.Insight#1]
It appears that several of the needed cmdlets are missing from the repo and when the module is installed using Install-Module. For instance, Set-InsightServer is missing.

**Comment by DamagedDingo** [comment]
Unfortunately, I was taken off this project about 6 months ago and no longer have access to a server to work on it. 
Hopefully, someone will pick it up to continue its progress. 

At the time I made this the API was only in BETA so its possible that things have changed anyway.
